# IoT project - Mood Detection - Dataset Preprocessing
## Vinaykumar Kulkarni

In [1]:
import numpy as np
import pandas as pd

Read the CSV 

In [12]:
hr = pd.read_csv("mmc2.csv")
tweet = pd.read_csv("mmc3.csv")

In [13]:
hr = hr.dropna()

In [14]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 411799 entries, 0 to 411798
Data columns (total 2 columns):
date_time    411799 non-null object
hr           411799 non-null int64
dtypes: int64(1), object(1)
memory usage: 9.4+ MB


In [15]:
tweet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1029 entries, 0 to 1028
Data columns (total 5 columns):
day_pos          1029 non-null int64
date_time        1029 non-null object
date_time_exp    1029 non-null object
sent_num         1029 non-null int64
text             1029 non-null object
dtypes: int64(2), object(3)
memory usage: 40.3+ KB


Change data format

In [16]:
hr["date_time"] = pd.to_datetime(hr["date_time"], format="%Y-%m-%d %H:%M:%S")
tweet["date_time"] = pd.to_datetime(tweet["date_time"], format="%Y-%m-%d %H:%M:%S")

Calculate minute difference from start of experiment to corelate tweet to HR

In [19]:
hr["hrdiff"] = (hr["date_time"] - pd.Timestamp('2016-05-10 00:00:00')).astype('timedelta64[m]')
tweet["twdiff"] = (tweet["date_time"] - pd.Timestamp('2016-05-10 00:00:00')).astype('timedelta64[m]')

In [20]:
print(hr)

                 date_time  hr   hrdiff
0      2016-05-10 00:00:05  89      0.0
1      2016-05-10 00:00:10  89      0.0
2      2016-05-10 00:00:25  89      0.0
3      2016-05-10 00:00:40  87      0.0
4      2016-05-10 00:00:50  88      0.0
5      2016-05-10 00:01:05  88      1.0
6      2016-05-10 00:01:10  88      1.0
7      2016-05-10 00:01:25  87      1.0
8      2016-05-10 00:01:40  87      1.0
9      2016-05-10 00:01:50  87      1.0
10     2016-05-10 00:01:55  88      1.0
11     2016-05-10 00:02:10  89      2.0
12     2016-05-10 00:02:20  90      2.0
13     2016-05-10 00:02:35  90      2.0
14     2016-05-10 00:02:50  90      2.0
15     2016-05-10 00:02:55  91      2.0
16     2016-05-10 00:03:10  91      3.0
17     2016-05-10 00:03:25  91      3.0
18     2016-05-10 00:03:30  92      3.0
19     2016-05-10 00:03:45  92      3.0
20     2016-05-10 00:04:00  91      4.0
21     2016-05-10 00:04:15  91      4.0
22     2016-05-10 00:04:30  91      4.0
23     2016-05-10 00:04:40  89      4.0


In [21]:
print(tweet)

      day_pos           date_time        date_time_exp  sent_num  \
0           1 2016-05-10 07:36:17  2016-05-10 07:30:00        -1   
1           2 2016-05-10 08:17:35  2016-05-10 08:15:00         1   
2           3 2016-05-10 09:04:16  2016-05-10 09:00:00         1   
3           4 2016-05-10 09:46:34  2016-05-10 09:45:00         1   
4           5 2016-05-10 10:31:37  2016-05-10 10:30:00        -1   
5           6 2016-05-10 11:17:33  2016-05-10 11:15:00         1   
6           7 2016-05-10 12:02:18  2016-05-10 12:00:00         1   
7           8 2016-05-10 12:42:01  2016-05-10 12:00:00         1   
8           9 2016-05-10 13:32:52  2016-05-10 13:30:00         1   
9          10 2016-05-10 14:25:35  2016-05-10 14:15:00         1   
10         11 2016-05-10 15:04:11  2016-05-10 15:00:00        -1   
11         12 2016-05-10 15:48:41  2016-05-10 15:45:00         1   
12         13 2016-05-10 16:44:50  2016-05-10 16:30:00         1   
13         14 2016-05-10 17:17:54  2016-05-10 17

In [22]:
df2 = pd.merge(hr, tweet, how='inner', left_on='hrdiff', right_on='twdiff')

In [23]:
df2.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 5909 entries, 0 to 5908
Data columns (total 9 columns):
date_time_x      5909 non-null datetime64[ns]
hr               5909 non-null int64
hrdiff           5909 non-null float64
day_pos          5909 non-null int64
date_time_y      5909 non-null datetime64[ns]
date_time_exp    5909 non-null object
sent_num         5909 non-null int64
text             5909 non-null object
twdiff           5909 non-null float64
dtypes: datetime64[ns](2), float64(2), int64(3), object(2)
memory usage: 461.6+ KB


In [24]:
print(df2)

             date_time_x   hr   hrdiff  day_pos         date_time_y  \
0    2016-05-10 08:17:05  102    497.0        2 2016-05-10 08:17:35   
1    2016-05-10 08:17:10  101    497.0        2 2016-05-10 08:17:35   
2    2016-05-10 08:17:25  101    497.0        2 2016-05-10 08:17:35   
3    2016-05-10 08:17:40   98    497.0        2 2016-05-10 08:17:35   
4    2016-05-10 08:17:50   98    497.0        2 2016-05-10 08:17:35   
5    2016-05-10 09:04:00   90    544.0        3 2016-05-10 09:04:16   
6    2016-05-10 09:04:05   92    544.0        3 2016-05-10 09:04:16   
7    2016-05-10 09:04:20   70    544.0        3 2016-05-10 09:04:16   
8    2016-05-10 09:04:30   69    544.0        3 2016-05-10 09:04:16   
9    2016-05-10 09:04:45   69    544.0        3 2016-05-10 09:04:16   
10   2016-05-10 09:04:50   69    544.0        3 2016-05-10 09:04:16   
11   2016-05-10 09:46:05  106    586.0        4 2016-05-10 09:46:34   
12   2016-05-10 09:46:10  108    586.0        4 2016-05-10 09:46:34   
13   2

In [18]:
tweetextra = tweet.as_matrix(columns=['sent_num', 'twdiff'])

In [19]:
tweetextra[0]

array([ -1., 601.])

In [20]:
newtweet = []
for tw in tweetextra:
    for i in range(-5,6):
        temp = np.copy(tw)
        temp[1] = temp[1]+i
        newtweet.append(temp)
    

In [21]:
newtweet

[array([ -1., 596.]),
 array([ -1., 597.]),
 array([ -1., 598.]),
 array([ -1., 599.]),
 array([ -1., 600.]),
 array([ -1., 601.]),
 array([ -1., 602.]),
 array([ -1., 603.]),
 array([ -1., 604.]),
 array([ -1., 605.]),
 array([ -1., 606.]),
 array([ -1., 647.]),
 array([ -1., 648.]),
 array([ -1., 649.]),
 array([ -1., 650.]),
 array([ -1., 651.]),
 array([ -1., 652.]),
 array([ -1., 653.]),
 array([ -1., 654.]),
 array([ -1., 655.]),
 array([ -1., 656.]),
 array([ -1., 657.]),
 array([  1., 673.]),
 array([  1., 674.]),
 array([  1., 675.]),
 array([  1., 676.]),
 array([  1., 677.]),
 array([  1., 678.]),
 array([  1., 679.]),
 array([  1., 680.]),
 array([  1., 681.]),
 array([  1., 682.]),
 array([  1., 683.]),
 array([  1., 715.]),
 array([  1., 716.]),
 array([  1., 717.]),
 array([  1., 718.]),
 array([  1., 719.]),
 array([  1., 720.]),
 array([  1., 721.]),
 array([  1., 722.]),
 array([  1., 723.]),
 array([  1., 724.]),
 array([  1., 725.]),
 array([  1., 774.]),
 array([  

In [22]:
tweetextradf = pd.DataFrame(data= newtweet, columns=['mood','twdiffextra'])

In [23]:
tweetextradf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11187 entries, 0 to 11186
Data columns (total 2 columns):
mood           11187 non-null float64
twdiffextra    11187 non-null float64
dtypes: float64(2)
memory usage: 174.9 KB


In [24]:
tweetextradf

mood  twdiffextra
0      -1.0        596.0
1      -1.0        597.0
2      -1.0        598.0
3      -1.0        599.0
4      -1.0        600.0
5      -1.0        601.0
6      -1.0        602.0
7      -1.0        603.0
8      -1.0        604.0
9      -1.0        605.0
10     -1.0        606.0
11     -1.0        647.0
12     -1.0        648.0
13     -1.0        649.0
14     -1.0        650.0
15     -1.0        651.0
16     -1.0        652.0
17     -1.0        653.0
18     -1.0        654.0
19     -1.0        655.0
20     -1.0        656.0
21     -1.0        657.0
22      1.0        673.0
23      1.0        674.0
24      1.0        675.0
25      1.0        676.0
26      1.0        677.0
27      1.0        678.0
28      1.0        679.0
29      1.0        680.0
...     ...          ...
11157   1.0      71910.0
11158   1.0      71911.0
11159   1.0      71912.0
11160   1.0      71913.0
11161   1.0      71914.0
11162   1.0      71915.0
11163   1.0      71916.0
11164   1.0      71917.0
11165  -1.0      71950.0
11166  -1.0      71951.0
11167  -1.0      71952.0
11168  -1.0      71953.0
11169  -1.0      71954.0
11170  -1.0      71955.0
11171  -1.0      71956.0
11172  -1.0      71957.0
11173  -1.0      71958.0
11174  -1.0      71959.0
11175  -1.0      71960.0
11176   1.0      71998.0
11177   1.0      71999.0
11178   1.0      72000.0
11179   1.0      72001.0
11180   1.0      72002.0
11181   1.0      72003.0
11182   1.0      72004.0
11183   1.0      72005.0
11184   1.0      72006.0
11185   1.0      72007.0
11186   1.0      72008.0

[11187 rows x 2 columns]

In [25]:
df2 = pd.merge(hr, tweetextradf, how='inner', left_on='hrdiff', right_on='twdiffextra')

In [26]:
df2

date_time     hr  steps       gsr  calories  temp   hrdiff  \
0     2016-08-15 09:56:00   94.0      0  0.000057       2.0  87.8    596.0   
1     2016-08-15 09:57:00   81.0      0  0.000058       1.5  87.8    597.0   
2     2016-08-15 09:58:00   87.0      0  0.000058       1.6  88.7    598.0   
3     2016-08-15 09:59:00   90.0      0  0.000058       1.7  88.7    599.0   
4     2016-08-15 10:00:00   93.0      0  0.000057       1.9  88.7    600.0   
5     2016-08-15 10:01:00   93.0      0  0.000058       1.8  88.7    601.0   
6     2016-08-15 10:02:00   93.0      0  0.000058       1.9  88.7    602.0   
7     2016-08-15 10:03:00   93.0      0  0.000058       1.8  88.7    603.0   
8     2016-08-15 10:04:00   97.0      0  0.000058       2.2  88.7    604.0   
9     2016-08-15 10:05:00   99.0     13  0.000058       2.3  88.7    605.0   
10    2016-08-15 10:06:00  103.0      0  0.000058       2.6  88.7    606.0   
11    2016-08-15 10:47:00  129.0      7  0.000057       9.1  87.8    647.0   
12    2016-08-15 10:48:00  117.0      0  0.000057       5.4  87.8    648.0   
13    2016-08-15 10:49:00  111.0     80  0.000056       4.5  87.8    649.0   
14    2016-08-15 10:50:00  102.0     39  0.000056       3.0  87.8    650.0   
15    2016-08-15 10:51:00   89.0     46  0.000057       2.0  87.8    651.0   
16    2016-08-15 10:52:00  111.0      0  0.000057       3.1  86.9    652.0   
17    2016-08-15 10:53:00  109.0      0  0.000058       3.0  86.9    653.0   
18    2016-08-15 10:54:00  114.0     30  0.000056       4.3  86.9    654.0   
19    2016-08-15 10:55:00  109.0      0  0.000056       3.0  86.9    655.0   
20    2016-08-15 10:56:00  106.0      0  0.000056       2.7  86.9    656.0   
21    2016-08-15 10:57:00  108.0      0  0.000059       2.8  86.9    657.0   
22    2016-08-15 11:13:00  104.0      0  0.000056       2.7  87.8    673.0   
23    2016-08-15 11:14:00  104.0      0  0.000057       2.6  87.8    674.0   
24    2016-08-15 11:15:00  109.0     55  0.000058       3.2  88.7    675.0   
25    2016-08-15 11:16:00  118.0     82  0.000058       6.0  88.7    676.0   
26    2016-08-15 11:17:00  110.0      0  0.000057       3.3  88.7    677.0   
27    2016-08-15 11:18:00  102.0      0  0.000059       2.6  88.7    678.0   
28    2016-08-15 11:19:00  117.0     51  0.000058       5.2  88.7    679.0   
29    2016-08-15 11:20:00  115.0     51  0.000057       4.7  88.7    680.0   
...                   ...    ...    ...       ...       ...   ...      ...   
11156 2016-10-03 22:30:00   95.0      0  0.000057       2.7  86.0  71910.0   
11157 2016-10-03 22:31:00   96.0      0  0.000057       2.7  86.0  71911.0   
11158 2016-10-03 22:32:00   93.0      0  0.000059       2.6  86.0  71912.0   
11159 2016-10-03 22:33:00   95.0      0  0.000058       2.6  86.0  71913.0   
11160 2016-10-03 22:34:00   95.0      0  0.000057       2.7  86.0  71914.0   
11161 2016-10-03 22:35:00   95.0      0  0.000058       2.6  86.0  71915.0   
11162 2016-10-03 22:36:00   95.0      0  0.000058       2.7  86.0  71916.0   
11163 2016-10-03 22:37:00   94.0      0  0.000059       2.6  86.0  71917.0   
11164 2016-10-03 23:10:00  100.0     20  0.000057       3.2  86.0  71950.0   
11165 2016-10-03 23:11:00  101.0     11  0.000055       3.4  86.0  71951.0   
11166 2016-10-03 23:12:00   95.0     20  0.000056       2.7  86.0  71952.0   
11167 2016-10-03 23:13:00  106.0     14  0.000055       5.4  85.1  71953.0   
11168 2016-10-03 23:14:00  103.0      0  0.000054       3.4  85.1  71954.0   
11169 2016-10-03 23:15:00   91.0      0  0.000054       2.4  84.2  71955.0   
11170 2016-10-03 23:16:00   88.0      0  0.000054       2.2  84.2  71956.0   
11171 2016-10-03 23:17:00   89.0      0  0.000054       2.2  84.2  71957.0   
11172 2016-10-03 23:18:00   90.0      0  0.000054       2.3  84.2  71958.0   
11173 2016-10-03 23:19:00   86.0      0  0.000054       2.0  85.1  71959.0   
11174 2016-10-03 23:20:00   87.0      0  0.000054       2.1  85.1  71960.0   
11175 2016-10-03 23:58:00   82.0      

In [27]:
result = df2[['hr','steps','gsr','calories','temp','mood']].copy()

In [28]:
result

hr  steps       gsr  calories  temp  mood
0       94.0      0  0.000057       2.0  87.8  -1.0
1       81.0      0  0.000058       1.5  87.8  -1.0
2       87.0      0  0.000058       1.6  88.7  -1.0
3       90.0      0  0.000058       1.7  88.7  -1.0
4       93.0      0  0.000057       1.9  88.7  -1.0
5       93.0      0  0.000058       1.8  88.7  -1.0
6       93.0      0  0.000058       1.9  88.7  -1.0
7       93.0      0  0.000058       1.8  88.7  -1.0
8       97.0      0  0.000058       2.2  88.7  -1.0
9       99.0     13  0.000058       2.3  88.7  -1.0
10     103.0      0  0.000058       2.6  88.7  -1.0
11     129.0      7  0.000057       9.1  87.8  -1.0
12     117.0      0  0.000057       5.4  87.8  -1.0
13     111.0     80  0.000056       4.5  87.8  -1.0
14     102.0     39  0.000056       3.0  87.8  -1.0
15      89.0     46  0.000057       2.0  87.8  -1.0
16     111.0      0  0.000057       3.1  86.9  -1.0
17     109.0      0  0.000058       3.0  86.9  -1.0
18     114.0     30  0.000056       4.3  86.9  -1.0
19     109.0      0  0.000056       3.0  86.9  -1.0
20     106.0      0  0.000056       2.7  86.9  -1.0
21     108.0      0  0.000059       2.8  86.9  -1.0
22     104.0      0  0.000056       2.7  87.8   1.0
23     104.0      0  0.000057       2.6  87.8   1.0
24     109.0     55  0.000058       3.2  88.7   1.0
25     118.0     82  0.000058       6.0  88.7   1.0
26     110.0      0  0.000057       3.3  88.7   1.0
27     102.0      0  0.000059       2.6  88.7   1.0
28     117.0     51  0.000058       5.2  88.7   1.0
29     115.0     51  0.000057       4.7  88.7   1.0
...      ...    ...       ...       ...   ...   ...
11156   95.0      0  0.000057       2.7  86.0   1.0
11157   96.0      0  0.000057       2.7  86.0   1.0
11158   93.0      0  0.000059       2.6  86.0   1.0
11159   95.0      0  0.000058       2.6  86.0   1.0
11160   95.0      0  0.000057       2.7  86.0   1.0
11161   95.0      0  0.000058       2.6  86.0   1.0
11162   95.0      0  0.000058       2.7  86.0   1.0
11163   94.0      0  0.000059       2.6  86.0   1.0
11164  100.0     20  0.000057       3.2  86.0  -1.0
11165  101.0     11  0.000055       3.4  86.0  -1.0
11166   95.0     20  0.000056       2.7  86.0  -1.0
11167  106.0     14  0.000055       5.4  85.1  -1.0
11168  103.0      0  0.000054       3.4  85.1  -1.0
11169   91.0      0  0.000054       2.4  84.2  -1.0
11170   88.0      0  0.000054       2.2  84.2  -1.0
11171   89.0      0  0.000054       2.2  84.2  -1.0
11172   90.0      0  0.000054       2.3  84.2  -1.0
11173   86.0      0  0.000054       2.0  85.1  -1.0
11174   87.0      0  0.000054       2.1  85.1  -1.0
11175   82.0      0  0.000059       1.7  91.4   1.0
11176   85.0      0  0.000059       2.0  91.4   1.0
11177   83.0      0  0.000060       1.7  91.4   1.0
11178   86.0      0  0.000060       2.0  91.4   1.0
11179   92.0      0  0.000060       2.5  91.4   1.0
11180   91.0      0  0.000061       2.4  91.4   1.0
11181   90.0      8  0.000063       2.5  91.4   1.0
11182   94.0      0  0.000062       2.5  91.4   1.0
11183  102.0     18  0.000063       3.8  91.4   1.0
11184   92.0      0  0.000062       2.7  91.4   1.0
11185  102.0     12  0.000064       3.3  91.4   1.0

[11186 rows x 6 columns]

In [29]:
result.to_csv("result_basic.csv", index= False)